version: '3.9'

services:
  backend:
    image: ghcr.io/gkg0139/int531-backend:latest
    container_name: backend
    restart: unless-stopped
    ports:
      - '8080:8080'
    environment:
      DB_HOST: database
      DB_PORT: 3306
      DB_NAME: int531
      DB_USER: root
      DB_PASSWORD: rootpassword
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/health']
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
    networks:
      - app-network

  database:
    image: mysql:5.7
    container_name: database
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: int531
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    internal: true

volumes:
  db_data:
    driver: local
