{
 "title": "Node Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\"}[1m]) * 100) by (instance, cpu)",
     "legendFormat": "CPU: {{cpu}}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100",
     "legendFormat": "Memory Used"
    }
   ]
  },
  {
   "title": "Disk Read/Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total[1m])) by (instance)",
     "legendFormat": "Disk read"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total[1m])) by (instance)",
     "legendFormat": "Disk write"
    }
   ]
  },
  {
   "title": "Disk Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\r\n  sum(node_filesystem_size_bytes{fstype!~\"tmpfs|overlay\"})\r\n  -\r\n  sum(node_filesystem_free_bytes{fstype!~\"tmpfs|overlay\"})\r\n)\r\n/\r\nsum(node_filesystem_size_bytes{fstype!~\"tmpfs|overlay\"})\r\n* 100\r\n",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}